// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33Sphr5340r7jUJsM_Ue5c4oPUR5ShCQ',
    appId: '1:459344716712:web:ba7a444e8d8f999c65b39d',
    messagingSenderId: '459344716712',
    projectId: 'jhkp-79fc8',
    authDomain: 'jhkp-79fc8.firebaseapp.com',
    storageBucket: 'jhkp-79fc8.firebasestorage.app',
    measurementId: 'G-RLK42ZMRSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh8r93eY91xKOJkRwZ2h89u_DNvLAC9Fc',
    appId: '1:459344716712:android:b7cfacd91c9b9c6665b39d',
    messagingSenderId: '459344716712',
    projectId: 'jhkp-79fc8',
    storageBucket: 'jhkp-79fc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoId_LvcJhi3ObwFCFUFajVPB4T7IdmWc',
    appId: '1:459344716712:ios:451a4ce8eee8b42365b39d',
    messagingSenderId: '459344716712',
    projectId: 'jhkp-79fc8',
    storageBucket: 'jhkp-79fc8.firebasestorage.app',
    iosBundleId: 'com.example.jhk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoId_LvcJhi3ObwFCFUFajVPB4T7IdmWc',
    appId: '1:459344716712:ios:451a4ce8eee8b42365b39d',
    messagingSenderId: '459344716712',
    projectId: 'jhkp-79fc8',
    storageBucket: 'jhkp-79fc8.firebasestorage.app',
    iosBundleId: 'com.example.jhk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC33Sphr5340r7jUJsM_Ue5c4oPUR5ShCQ',
    appId: '1:459344716712:web:b43c05deaabe8b1f65b39d',
    messagingSenderId: '459344716712',
    projectId: 'jhkp-79fc8',
    authDomain: 'jhkp-79fc8.firebaseapp.com',
    storageBucket: 'jhkp-79fc8.firebasestorage.app',
    measurementId: 'G-FPY0WQ92PV',
  );
}
